spring:
    application:
      name: user
    h2:
      console:
        enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
    jpa:
      hibernate:
        ddl-auto: update
logging:
  level:
    sql: info